import type { Metadata } from 'next';
import { Montserrat, Fraunces } from 'next/font/google';
import './globals.css';

const montserrat = Montserrat({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const fraunces = Fraunces({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${montserrat.variable} ${fraunces.variable} antialiased font-sans`}
			>
				{children}
			</body>
		</html>
	);
}
